### PR TITLE
Resend a PR for RVV feature support in GCC (intrinsics+auto-vectorization)

### PR DESCRIPTION
**Pull request by zhongjuzhe**
Last time I send a PR for RVV features but it turns out that it hard for reviewers to review the code due to the explosion of RVV testcases. I am sorry for that. It's my fault. So I remove rvv tests and send a new PR for it. The RVV testcases will be commited in the next commit. The old PR is here: https://github.com/riscv-collab/riscv-gcc/pull/329

Copy from the Last PR:
Hi, Our company, RiVAI Technology supported RVV features and decided to open source the GCC. So we  make a PR for it. So far it is not stable yet, we put it in the foundation repo first and keep updating it. After finishing all review and GCC become stable. Our company has assign GCC FSF, so we will finally send a PR to GCC FSF. Thanks~
Enable RVV intrinsic support:
   Users can either use 
   `#pragma riscv intrinsic "vector"`
   or 
   `#include <riscv_vector.h>`

  Enable auto-vectorization support:
   use `-mrvv` compile option.
  Enable VLS auto-vectorization support:
   use `-mrvv -mriscv-vector-bits=N` (N can be 128 ~ 65536)

code:
```c
#include <stddef.h>
#include <stdint.h>


void __attribute__ ((noinline, noclone))
foo(int8_t * restrict a, int8_t * restrict b, int16_t * restrict c, size_t m)
{
  for (size_t i = 0; i < m; i++)
    c[i] += (int16_t)a[i] * (int16_t)b[i];
}
```
Example of VLA autovectorization:
`riscv64-rivai-elf-gcc -mrvv -O3 -S auto.c`
asm:
```
foo:
        beq     a3,zero,.L1
        csrr    a6,vlenb
        srai    a5,a6,1
.L3:
        vsetvli a4,a3,e16,m1,ta,mu
        vle16.v v24,(a2)
        vle8.v  v26,(a0)
        vle8.v  v25,(a1)
        sub     a3,a3,a4
        vsetvli zero,zero,e8,mf2,ta,mu
        vwmacc.vv       v24,v26,v25
        vse16.v v24,(a2)
        add     a1,a1,a5
        add     a2,a2,a6
        add     a0,a0,a5
        bne     a3,zero,.L3
.L1:
        ret
```
Example of VLS autovectorization:
`riscv64-rivai-elf-gcc -mrvv -mriscv-vector-bits=128 -O3 -S auto.c`
asm:
```
foo:
        beq     a3,zero,.L10
.L3:
        vsetvli a5,a3,e16,m1,ta,mu
        vle16.v v24,(a2)
        vle8.v  v26,(a0)
        vle8.v  v25,(a1)
        sub     a3,a3,a5
        vsetvli zero,zero,e8,mf2,ta,mu
        vwmacc.vv       v24,v26,v25
        vse16.v v24,(a2)
        addi    a1,a1,8
        addi    a2,a2,16
        addi    a0,a0,8
        bne     a3,zero,.L3
.L10:
        ret
```

More information for reviewers:
There are total `81` files changed in the development. Reviewers can click on the `Files changed` to review the code change.

1. RVV headers organization:
The `riscv-gcc/gcc/config/riscv/riscv_vector.h` is the headers of RVV intrinsics. The organization is the same as ARM SVE. The implementation is intentionally short. Because it can reduce the header file size and reduce compilation time. 

2. RVV intrinsic support:
The RVV intrinsic supports are all on the backend of riscv.
The major part of the files are:
`riscv-gcc/gcc/config/riscv/riscv-vector-builtins.cc`
`riscv-gcc/gcc/config/riscv/riscv-vector-builtins.def`
`riscv-gcc/gcc/config/riscv/riscv-vector-builtins-functions.cc`
`riscv-gcc/gcc/config/riscv/riscv-vector-builtins-functions.def`
`riscv-gcc/gcc/config/riscv/riscv-vector-builtins-functions.h`
`riscv-gcc/gcc/config/riscv/riscv-vector-builtins.h`
`riscv-gcc/gcc/config/riscv/riscv-vector-builtins-iterators.def`
`riscv-gcc/gcc/config/riscv/vector.md`

3. vsevl strategy:
The strategy of RVV GCC are almost the same as implementation of LLVM. The major code is
`riscv-gcc/gcc/config/riscv/riscv-insert-vsetvli.cc`

4. Vector length specific support:
In RVV spec, the maximum vector-length can be 65536 which overflows in poly_uint16. So we add `poly_uint_for_mode` type to support it. To support it, we changed the middle-end of GCC.

5. Auto-vectorizaiton support:
To support it, we changed a lot in the middle-end and add so many standard patterns for it.
The backend support:`riscv-gcc/gcc/config/riscv/vectorization.md`
The middle-end additional patterns we add are listed in the:`riscv-gcc/gcc/optabs.def`

### CODE REVIEW

**Comment by kito-cheng** [comment]
I just using this PR to code review:
- ACLE is appeared several times in the implementation,  do you mind remove or rename those term?
```
$ grep acle * -i
riscv-vector-builtins.cc:/* ACLE support for RISCV VECTOR
riscv-vector-builtins.cc:/* The maximum number of vectors in an ACLE tuple type.  */
riscv-vector-builtins.cc:tree acle_vector_types[MAX_TUPLE_SIZE][NUM_VECTOR_TYPES + 1][NUM_LMUL + 1];
riscv-vector-builtins.cc:   mangling of the type.  ACLE_NAME is the <riscv_vector.h> name of the type.
riscv-vector-builtins.cc:         /* abi_name and acle_name follows vector type implementation in LLVM.
riscv-vector-builtins.cc:            acle_name = vint8mf8_t.
riscv-vector-builtins.cc:  char acle_name[NAME_MAXLEN] = { 0 };
riscv-vector-builtins.cc:  snprintf (acle_name, NAME_MAXLEN, "v%s%s_t",
riscv-vector-builtins.cc:  tree id = get_identifier (acle_name);
riscv-vector-builtins.cc:  /* Record the new ACLE type if pushdecl succeeded without error.  Use
riscv-vector-builtins.cc:  acle_vector_types[0][type][lmul] = vectype;
riscv-vector-builtins.cc:  tree vector_type = acle_vector_types[0][type][lmul];
riscv-vector-builtins.cc:  acle_vector_types[num_vectors - 1][type][lmul] = tuple_type;
riscv-vector-builtins.cc:/* Return true if TYPE is a built-in RVV type defined by the ABI or ACLE.  */
riscv-vector-builtins-functions.cc:/* The maximum number of vectors in an ACLE tuple type.  */
riscv-vector-builtins-functions.cc:    acle_vector_types[MAX_TUPLE_SIZE][NUM_VECTOR_TYPES + 1][NUM_LMUL + 1];
riscv-vector-builtins-functions.cc:/* Return the ACLE type vbool##LMUL##_t.  */
riscv-vector-builtins-functions.cc:  return acle_vector_types[0][VECTOR_TYPE_bool][index];
riscv-vector-builtins-functions.cc:/* Return the ACLE type for machine_mode && lmul_value_index && bool u.  */
riscv-vector-builtins-functions.cc:        return acle_vector_types[0][VECTOR_TYPE_bool][lmul];
riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint8][lmul]
riscv-vector-builtins-functions.cc:                      : acle_vector_types[0][VECTOR_TYPE_int8][lmul];
riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint16][lmul]
riscv-vector-builtins-functions.cc:                      : acle_vector_types[0][VECTOR_TYPE_int16][lmul];
riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint32][lmul]
riscv-vector-builtins-functions.cc:                      : acle_vector_types[0][VECTOR_TYPE_int32][lmul];
riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint64][lmul]
riscv-vector-builtins-functions.cc:                      : acle_vector_types[0][VECTOR_TYPE_int64][lmul];
riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[0][VECTOR_TYPE_float16][lmul];
riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[0][VECTOR_TYPE_float32][lmul];
riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[0][VECTOR_TYPE_float64][lmul];
riscv-vector-builtins-functions.cc:/* Return the ACLE type for machine_mode && lmul_value_index && bool u.  */
riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[nelt - 1][VECTOR_TYPE_uint8][lmul]
riscv-vector-builtins-functions.cc:                      : acle_vector_types[nelt - 1][VECTOR_TYPE_int8][lmul];
riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[nelt - 1][VECTOR_TYPE_uint16][lmul]
riscv-vector-builtins-functions.cc:                      : acle_vector_types[nelt - 1][VECTOR_TYPE_int16][lmul];
riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[nelt - 1][VECTOR_TYPE_uint32][lmul]
riscv-vector-builtins-functions.cc:                      : acle_vector_types[nelt - 1][VECTOR_TYPE_int32][lmul];
riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[nelt - 1][VECTOR_TYPE_uint64][lmul]
riscv-vector-builtins-functions.cc:                      : acle_vector_types[nelt - 1][VECTOR_TYPE_int64][lmul];
riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[nelt - 1][VECTOR_TYPE_float16][lmul];
riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[nelt - 1][VECTOR_TYPE_float32][lmul];
riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[nelt - 1][VECTOR_TYPE_float64][lmul];
riscv-vector-builtins-functions.cc:      vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint32][lmul]
riscv-vector-builtins-functions.cc:                  : acle_vector_types[0][VECTOR_TYPE_int32][lmul];
riscv-vector-builtins-functions.cc:  error_at (location, "ACLE function %qD requires ISA extension %qs", fndecl,
riscv-vector-builtins-functions.h:/* ACLE support for RISCV VECTOR (function_base classes)
riscv-vector-builtins.h:/* ACLE support for RISCV VECTOR
riscv-vector-builtins.h:/* The full name of an RVV ACLE function is the concatenation of:
riscv-vector-builtins.h:     conform to the ACLE specification
```
- Could you split the big one patch into smaller smaller chunk:
    - e.g. 1. Adding type support, 2. Basic type load/store/spill support including stack manipulation 3. Minimal intrinsic support (vle + vse) 4. Add single width binary operation for integer (add, mul...) 5. Add widen operation...and so on

**Comment by zhongjuzhe** [comment]
> acle_vector_types

Yeah, I just copied from arm. For example: acle_vector_types. What name do you prefer? like "rvv_vector_type"?   
For your review, I am gonna split them into several small patches. Thank you ~

**Comment by zhongjuzhe** [comment]
> I just using this PR to code review:
> 
> * ACLE is appeared several times in the implementation,  do you mind remove or rename those term?
> 
> ```
> $ grep acle * -i
> riscv-vector-builtins.cc:/* ACLE support for RISCV VECTOR
> riscv-vector-builtins.cc:/* The maximum number of vectors in an ACLE tuple type.  */
> riscv-vector-builtins.cc:tree acle_vector_types[MAX_TUPLE_SIZE][NUM_VECTOR_TYPES + 1][NUM_LMUL + 1];
> riscv-vector-builtins.cc:   mangling of the type.  ACLE_NAME is the <riscv_vector.h> name of the type.
> riscv-vector-builtins.cc:         /* abi_name and acle_name follows vector type implementation in LLVM.
> riscv-vector-builtins.cc:            acle_name = vint8mf8_t.
> riscv-vector-builtins.cc:  char acle_name[NAME_MAXLEN] = { 0 };
> riscv-vector-builtins.cc:  snprintf (acle_name, NAME_MAXLEN, "v%s%s_t",
> riscv-vector-builtins.cc:  tree id = get_identifier (acle_name);
> riscv-vector-builtins.cc:  /* Record the new ACLE type if pushdecl succeeded without error.  Use
> riscv-vector-builtins.cc:  acle_vector_types[0][type][lmul] = vectype;
> riscv-vector-builtins.cc:  tree vector_type = acle_vector_types[0][type][lmul];
> riscv-vector-builtins.cc:  acle_vector_types[num_vectors - 1][type][lmul] = tuple_type;
> riscv-vector-builtins.cc:/* Return true if TYPE is a built-in RVV type defined by the ABI or ACLE.  */
> riscv-vector-builtins-functions.cc:/* The maximum number of vectors in an ACLE tuple type.  */
> riscv-vector-builtins-functions.cc:    acle_vector_types[MAX_TUPLE_SIZE][NUM_VECTOR_TYPES + 1][NUM_LMUL + 1];
> riscv-vector-builtins-functions.cc:/* Return the ACLE type vbool##LMUL##_t.  */
> riscv-vector-builtins-functions.cc:  return acle_vector_types[0][VECTOR_TYPE_bool][index];
> riscv-vector-builtins-functions.cc:/* Return the ACLE type for machine_mode && lmul_value_index && bool u.  */
> riscv-vector-builtins-functions.cc:        return acle_vector_types[0][VECTOR_TYPE_bool][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint8][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[0][VECTOR_TYPE_int8][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint16][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[0][VECTOR_TYPE_int16][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint32][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[0][VECTOR_TYPE_int32][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint64][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[0][VECTOR_TYPE_int64][lmul];
> riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[0][VECTOR_TYPE_float16][lmul];
> riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[0][VECTOR_TYPE_float32][lmul];
> riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[0][VECTOR_TYPE_float64][lmul];
> riscv-vector-builtins-functions.cc:/* Return the ACLE type for machine_mode && lmul_value_index && bool u.  */
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[nelt - 1][VECTOR_TYPE_uint8][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[nelt - 1][VECTOR_TYPE_int8][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[nelt - 1][VECTOR_TYPE_uint16][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[nelt - 1][VECTOR_TYPE_int16][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[nelt - 1][VECTOR_TYPE_uint32][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[nelt - 1][VECTOR_TYPE_int32][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[nelt - 1][VECTOR_TYPE_uint64][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[nelt - 1][VECTOR_TYPE_int64][lmul];
> riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[nelt - 1][VECTOR_TYPE_float16][lmul];
> riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[nelt - 1][VECTOR_TYPE_float32][lmul];
> riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[nelt - 1][VECTOR_TYPE_float64][lmul];
> riscv-vector-builtins-functions.cc:      vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint32][lmul]
> riscv-vector-builtins-functions.cc:                  : acle_vector_types[0][VECTOR_TYPE_int32][lmul];
> riscv-vector-builtins-functions.cc:  error_at (location, "ACLE function %qD requires ISA extension %qs", fndecl,
> riscv-vector-builtins-functions.h:/* ACLE support for RISCV VECTOR (function_base classes)
> riscv-vector-builtins.h:/* ACLE support for RISCV VECTOR
> riscv-vector-builtins.h:/* The full name of an RVV ACLE function is the concatenation of:
> riscv-vector-builtins.h:     conform to the ACLE specification
> ```
> 
> * Could you split the big one patch into smaller smaller chunk:
>   
>   * e.g. 1. Adding type support, 2. Basic type load/store/spill support including stack manipulation 3. Minimal intrinsic support (vle + vse) 4. Add single width binary operation for integer (add, mul...) 5. Add widen operation...and so on


Yeah, I just copied from arm. For example: acle_vector_types. What name do you prefer? like "rvv_vector_type"?   
For your review, I am gonna split them into several small patches. Thank you ~

**Comment by zhongjuzhe** [comment]
> I just using this PR to code review:
> 
> * ACLE is appeared several times in the implementation,  do you mind remove or rename those term?
> 
> ```
> $ grep acle * -i
> riscv-vector-builtins.cc:/* ACLE support for RISCV VECTOR
> riscv-vector-builtins.cc:/* The maximum number of vectors in an ACLE tuple type.  */
> riscv-vector-builtins.cc:tree acle_vector_types[MAX_TUPLE_SIZE][NUM_VECTOR_TYPES + 1][NUM_LMUL + 1];
> riscv-vector-builtins.cc:   mangling of the type.  ACLE_NAME is the <riscv_vector.h> name of the type.
> riscv-vector-builtins.cc:         /* abi_name and acle_name follows vector type implementation in LLVM.
> riscv-vector-builtins.cc:            acle_name = vint8mf8_t.
> riscv-vector-builtins.cc:  char acle_name[NAME_MAXLEN] = { 0 };
> riscv-vector-builtins.cc:  snprintf (acle_name, NAME_MAXLEN, "v%s%s_t",
> riscv-vector-builtins.cc:  tree id = get_identifier (acle_name);
> riscv-vector-builtins.cc:  /* Record the new ACLE type if pushdecl succeeded without error.  Use
> riscv-vector-builtins.cc:  acle_vector_types[0][type][lmul] = vectype;
> riscv-vector-builtins.cc:  tree vector_type = acle_vector_types[0][type][lmul];
> riscv-vector-builtins.cc:  acle_vector_types[num_vectors - 1][type][lmul] = tuple_type;
> riscv-vector-builtins.cc:/* Return true if TYPE is a built-in RVV type defined by the ABI or ACLE.  */
> riscv-vector-builtins-functions.cc:/* The maximum number of vectors in an ACLE tuple type.  */
> riscv-vector-builtins-functions.cc:    acle_vector_types[MAX_TUPLE_SIZE][NUM_VECTOR_TYPES + 1][NUM_LMUL + 1];
> riscv-vector-builtins-functions.cc:/* Return the ACLE type vbool##LMUL##_t.  */
> riscv-vector-builtins-functions.cc:  return acle_vector_types[0][VECTOR_TYPE_bool][index];
> riscv-vector-builtins-functions.cc:/* Return the ACLE type for machine_mode && lmul_value_index && bool u.  */
> riscv-vector-builtins-functions.cc:        return acle_vector_types[0][VECTOR_TYPE_bool][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint8][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[0][VECTOR_TYPE_int8][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint16][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[0][VECTOR_TYPE_int16][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint32][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[0][VECTOR_TYPE_int32][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint64][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[0][VECTOR_TYPE_int64][lmul];
> riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[0][VECTOR_TYPE_float16][lmul];
> riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[0][VECTOR_TYPE_float32][lmul];
> riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[0][VECTOR_TYPE_float64][lmul];
> riscv-vector-builtins-functions.cc:/* Return the ACLE type for machine_mode && lmul_value_index && bool u.  */
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[nelt - 1][VECTOR_TYPE_uint8][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[nelt - 1][VECTOR_TYPE_int8][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[nelt - 1][VECTOR_TYPE_uint16][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[nelt - 1][VECTOR_TYPE_int16][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[nelt - 1][VECTOR_TYPE_uint32][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[nelt - 1][VECTOR_TYPE_int32][lmul];
> riscv-vector-builtins-functions.cc:          vectype = u ? acle_vector_types[nelt - 1][VECTOR_TYPE_uint64][lmul]
> riscv-vector-builtins-functions.cc:                      : acle_vector_types[nelt - 1][VECTOR_TYPE_int64][lmul];
> riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[nelt - 1][VECTOR_TYPE_float16][lmul];
> riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[nelt - 1][VECTOR_TYPE_float32][lmul];
> riscv-vector-builtins-functions.cc:          vectype = acle_vector_types[nelt - 1][VECTOR_TYPE_float64][lmul];
> riscv-vector-builtins-functions.cc:      vectype = u ? acle_vector_types[0][VECTOR_TYPE_uint32][lmul]
> riscv-vector-builtins-functions.cc:                  : acle_vector_types[0][VECTOR_TYPE_int32][lmul];
> riscv-vector-builtins-functions.cc:  error_at (location, "ACLE function %qD requires ISA extension %qs", fndecl,
> riscv-vector-builtins-functions.h:/* ACLE support for RISCV VECTOR (function_base classes)
> riscv-vector-builtins.h:/* ACLE support for RISCV VECTOR
> riscv-vector-builtins.h:/* The full name of an RVV ACLE function is the concatenation of:
> riscv-vector-builtins.h:     conform to the ACLE specification
> ```
> 
> * Could you split the big one patch into smaller smaller chunk:
>   
>   * e.g. 1. Adding type support, 2. Basic type load/store/spill support including stack manipulation 3. Minimal intrinsic support (vle + vse) 4. Add single width binary operation for integer (add, mul...) 5. Add widen operation...and so on

Yes, I am gonna rename it as riscv_vector_types. And I need some time to configure out how to split the patch into small chunks. Thank you.

**Comment by kito-cheng** [comment]
> Yeah, I just copied from arm. For example: acle_vector_types. What name do you prefer? like "rvv_vector_type"?

rvv_vector_type is OK to me :)

**Comment by zhongjuzhe** [comment]
> > Yeah, I just copied from arm. For example: acle_vector_types. What name do you prefer? like "rvv_vector_type"?
> 
> rvv_vector_type is OK to me :)

I am now splitting the patch. I am gonna splitting every important features into several https://github.com/riscv-collab/riscv-gcc/pull/334. For example: the stack manipulation.Is that OK?

**Pull request merged**
