### PR TITLE
Add Non-Tuple API for unit-stride/strided of Zvlsseg

### PR DESCRIPTION
**Pull request by rjiejie**

### CODE REVIEW

**Comment by rjiejie** [comment]
@kito-cheng review this patch please :)

**Comment by rjiejie** [comment]
@kito-cheng Hello ?

**Comment by kito-cheng** [comment]
Could you add testcase for that?

**Comment by rjiejie** [comment]
Okay, I will append test case in this week :)

**Comment by rjiejie** [comment]
@kito-cheng is it ok ?

**Comment by rjiejie** [comment]
@kito-cheng ping ...

**Comment by kito-cheng** [comment]
Verified with internal API checker, thanks :)

**Pull request merged**
