### PR TITLE
Fix rvv-intrinsic.exp

### PR DESCRIPTION
**Pull request by zqb-all**
1.rename `_m_ta`/`m_tu` to `_tam`/`_tum`
2.add dest operand for vslideup/vslidedown `_ta` and `_tama`

### CODE REVIEW

**Comment by zqb-all** [comment]
Fix base on https://github.com/riscv-non-isa/rvv-intrinsic-doc/commit/765807057dc4a0baa9bb67887757fa305e4b6990
I'm not sure if there are any scripts to regenerate these test code, so i just replace them with sed.

**Comment by zhongjuzhe** [comment]
Oh, thank you for discovering my silly mistakes.
Take a look at this : 
https://github.com/riscv-collab/riscv-gcc/tree/riscv-gcc-rvv-next/gcc/testsuite/gcc.target/riscv/rvv/intrinsic

You will find 2 directories have same tests: a1u and alu.
The tests in alu are all updated to the latest RVV intrinsic documents as my downstream script update.

I forgot to remove the redundant obsolete directory a1u. Can you send a PR to remove it? Thanks.

**Comment by zqb-all** [comment]
I see, alu is new version, now I update the PR to remove a1u

**Comment by zhongjuzhe** [comment]
Thanks, commited.

**Pull request merged**
