### PR TITLE
Bugfix spill/fill error of segment types

### PR DESCRIPTION
**Pull request by rjiejie**

### CODE REVIEW

**Comment by rjiejie** [comment]
@kito-cheng Have any free time to review this patch ?

**Comment by monkchiang** [comment]
Could you provide a test case for this patch?

**Comment by rjiejie** [comment]
> Could you provide a test case for this patch?

The test case for reload is a litter hard for me,
and I have tested ok in some applications as OpenCV :)

**Comment by rjiejie** [comment]
@kito-cheng Any comments ?

**Comment by rjiejie** [comment]
> @rjiejie Could you use this to create a testcas?
> 
> ```
> #include <riscv_vector.h>
> 
> void foo(){
> 
>   vint32m1x2_t x;
>   asm volatile ("#%0":"=vr"(x));
>   asm volatile ("###":::"v0", "v1", "v2", "v3", "v4", "v5", "v6", "v7", "v8", "v9", "v10", "v11", "v12", "v13", "v14", "v15", "v16", "v17", "v18", "v19", "v20", "v21", "v22", "v23", "v24", "v25", "v26", "v27", "v28", "v29", "v30", "v31", "memory");
>   asm volatile ("#%0"::"vr"(x));
> }
> ```

Ok, I will make it soon.

**Comment by rjiejie** [comment]
@kito-cheng Add testcase

**Comment by rjiejie** [comment]
@kito-cheng Any comments else ?

**Comment by rjiejie** [comment]
@kito-cheng Ping ...

**Comment by rjiejie** [comment]
@kito-cheng Hello ?

**Comment by kito-cheng** [comment]
Apology for the long review period...just verified the correctness of this patch, thanks!

**Pull request merged**
