### PR TITLE
  Support RVV Features including intrinsic and auto-vectorization

### PR DESCRIPTION
**Pull request by zhongjuzhe**
Hi, Our company, RiVAI Technology supported RVV features and decided to open source the GCC. So we  make a PR for it. So far it is not stable yet, we put it in the foundation repo first and keep updating it. After finishing all review and GCC become stable. Our company has assign GCC FSF, so we will finally send a PR to GCC FSF. Thanks~
Enable RVV intrinsic support:
   Users can either use 
   `#pragma riscv intrinsic "vector"`
   or 
   `#include <riscv_vector.h>`

  Enable auto-vectorization support:
   use `-mrvv` compile option.
  Enable VLS auto-vectorization support:
   use `-mrvv -mriscv-vector-bits=N` (N can be 128 ~ 65536)

code:
```c
#include <stddef.h>
#include <stdint.h>


void __attribute__ ((noinline, noclone))
foo(int8_t * restrict a, int8_t * restrict b, int16_t * restrict c, size_t m)
{
  for (size_t i = 0; i < m; i++)
    c[i] += (int16_t)a[i] * (int16_t)b[i];
}
```
Example of VLA autovectorization:
`riscv64-rivai-elf-gcc -mrvv -O3 -S auto.c`
asm:
```
foo:
        beq     a3,zero,.L1
        csrr    a6,vlenb
        srai    a5,a6,1
.L3:
        vsetvli a4,a3,e16,m1,ta,mu
        vle16.v v24,(a2)
        vle8.v  v26,(a0)
        vle8.v  v25,(a1)
        sub     a3,a3,a4
        vsetvli zero,zero,e8,mf2,ta,mu
        vwmacc.vv       v24,v26,v25
        vse16.v v24,(a2)
        add     a1,a1,a5
        add     a2,a2,a6
        add     a0,a0,a5
        bne     a3,zero,.L3
.L1:
        ret
```
Example of VLS autovectorization:
`riscv64-rivai-elf-gcc -mrvv -mriscv-vector-bits=128 -O3 -S auto.c`
asm:
```
foo:
        beq     a3,zero,.L10
.L3:
        vsetvli a5,a3,e16,m1,ta,mu
        vle16.v v24,(a2)
        vle8.v  v26,(a0)
        vle8.v  v25,(a1)
        sub     a3,a3,a5
        vsetvli zero,zero,e8,mf2,ta,mu
        vwmacc.vv       v24,v26,v25
        vse16.v v24,(a2)
        addi    a1,a1,8
        addi    a2,a2,16
        addi    a0,a0,8
        bne     a3,zero,.L3
.L10:
        ret
```

### CODE REVIEW

**Comment by kito-cheng** [comment]
Thanks for contribute such amazing works! I guess I need few more day to review that, and I expect that would be a long time fight :p

**Comment by zhongjuzhe** [comment]
> Thanks for contribute such amazing works! I guess I need few more day to review that, and I expect that will take long time and many rounds :p

Yeah, we are expecting your advise. And also I give you a list that I plan to do in the future before send a PR to GCC FSF:
1.Add more tests for auto-vectorization.
2.enable vect.exp(the vectorization test in GCC in testsuite) in riscv and fix bugs.
3.Support  C++ overload intrinsic functions.
4.Support force gcc to vectorize the loop with particular vectorization width like "#pragma clang loop vectorize" in the Clang.
5.Cost Model of RVV.
By the way, we are reconstitute part of the codes and add more tests for auto-vectorization. Soon we will update it. Thanks~

**Comment by zhongjuzhe** [comment]
> Thanks for contribute such amazing works! I guess I need few more day to review that, and I expect that will take long time and many rounds :p

Hi, I deleted the testcase reopen a PR for it. This is the linke https://github.com/riscv-collab/riscv-gcc/pull/330. I think it is more convinient for you to review. I will add testcase later after you reviewed.

**Comment by LiQi19970428** [comment]
@zhongjuzhe 
Hi, I would like to know how you implemented this functionality. Is there any reference articles about the process of auto-vectorization with RVV support?
Thank you very much.

**Comment by zhongjuzhe** [comment]
> 

In case of intrinsic builtin framework, I reference ARM SVE GCC.
In case of insert vsetvli pass, I reference LLVM.
These references are the codes in GCC and LLVM.

In case of auto-vectoriztion, unfortunately the upstream GCC doesn't support auto-vectorization be appropriate for RVV.
RVV auto-vectorization support needs so many middle-end changes and it is not easy to understand.
The only references are GCC internal and RVV ISA spec.

**Pull request closed without merging**
